### ISSUE TITLE
Allow saving and loading form contents

### ISSUE THREAD

**Issue by nephros** [sailfishos-chum/bugger#14]
at least the last unsubmitted one

**Comment by nephros** [comment]
I wonder if a Page can simply be serialized to JSON, and later PageStack.replace()-ed...

**Comment by thigg** [comment]
It would be easy to bind everything  to a javascript object, serialize that and load it later

**Comment by nephros** [comment]
Please see branch ['autosave'](https://github.com/sailfishos-chum/bugger/compare/autosave?expand=1) for a first try.

**Comment by nephros** [comment]
So that implementation works satisfactorily, modulo some minor issues.

But I just realized that loading and storing using XMLHttpRequests is quite silly (esp. loading).
This really must be switched to LocalStorage.

**Comment by nephros** [comment]
Implemented in 0.9.7 (9f9d45fd2a)
